## World Cup Players Data

In [87]:
data = pd.read_csv('wc2026_players.csv')
data.head()

,team_name,player_name,birth_country,citizenship,representing,data_complete
0,Czech Republic,Matěj Kovář,Czech Republic,Czech Republic,Czech Republic,True
1,Czech Republic,David Zima,NaN,NaN,Czech Republic,False
2,Czech Republic,Tomáš Holeš,Czech Republic,Czech Republic,Czech Republic,True
3,Czech Republic,Robin Hranáč,Czech Republic,Czech Republic,Czech Republic,True
4,Czech Republic,Vladimír Coufal,Czech Republic,Czech Republic,Czech Republic,True

In [89]:
len(data)

1248

## Missing Data
Birth Country and Citizenship were not available for all players

In [93]:
data.loc[:,['representing','birth_country','citizenship']].isnull().agg('sum')

representing       0
birth_country    315
citizenship      308
dtype: int64

In [85]:
(data.loc[:,['representing','birth_country','citizenship']].isnull().agg('sum')/len(data)).round(4)*100

representing      0.00
birth_country    25.24
citizenship      24.68
dtype: float64

In [91]:
complete_data = data.loc[~data.birth_country.isnull(),:]

## Born Here, Playing There

In [106]:
complete_data.loc[:,'born_here_playing_there'] = (complete_data.birth_country==complete_data.representing).astype('int8')
complete_data.loc[:,'dual_citizens'] = (complete_data.citizenship==complete_data.representing).astype('int8')
complete_data.loc[complete_data.birth_country=='France',].head(24)

,team_name,player_name,birth_country,citizenship,representing,data_complete,born_here_playing_there,citizen_here_playing_there
167,Qatar,Karim Boudiaf,France,France; Qatar,Qatar,True,0,0
234,Haiti,Johny Placide,France,France; Haiti,Haiti,True,0,0
241,Haiti,Martin Expérience,France,France; Haiti,Haiti,True,0,0
242,Haiti,Duckens Nazon,France,France; Haiti,Haiti,True,0,0
243,Haiti,Jean-Ricner Bellegarde,France,France; Haiti,Haiti,True,0,0
245,Haiti,Alexandre Pierre,France,France; Haiti,Haiti,True,0,0
249,Haiti,Lenny Joseph,France,France; Haiti,Haiti,True,0,0
251,Haiti,Wilson Isidor,France,France; Haiti,Haiti,True,0,0
252,Haiti,Yassin Fortuné,France,France; Haiti,Haiti,True,0,0
255,Haiti,Jean-Kévin Duverne,France,France; Haiti,Haiti,True,0,0
258,Haiti,Dominique Simon,France,France; Haiti,Haiti,True,0,0
265,Morocco,Ayyoub Bouaddi,France,France; Morocco,Morocco,True,0,0
273,Morocco,Issa Diop,France,France; Morocco,Morocco,True,0,0
274,Morocco,Samir El Mourabet,France,France; Morocco,Morocco,True,0,0
275,Morocco,Gessime Yassine,France,France,Morocco,True,0,0
283,Morocco,Neil El Aynaoui,France,France; Morocco,Morocco,True,0,0
494,Ivory Coast,Yahia Fofana,France,France; Ivory Coast,Ivory Coast,True,0,0
499,Ivory Coast,Seko Fofana,France,France; Ivory Coast,Ivory Coast,True,0,0
502,Ivory Coast,Ange-Yoan Bonny,France,France; Ivory Coast,Ivory Coast,True,0,0
505,Ivory Coast,Elye Wahi,France,France; Ivory Coast,Ivory Coast,True,0,0
510,Ivory Coast,Guéla Doué,France,France; Ivory Coast,Ivory Coast,True,0,0
512,Ivory Coast,Nicolas Pépé,France,France,Ivory Coast,True,0,0
600,Tunisia,Montassar Talbi,France,France; Tunisia,Tunisia,True,0,0
603,Tunisia,Dylan Bronn,France,France; Tunisia,Tunisia,True,0,0

In [95]:

(
    (complete_data.birth_country==complete_data.representing).value_counts(normalize=True),
    (complete_data.birth_country==complete_data.representing).value_counts(normalize=False)
)

(True     0.771704
 False    0.228296
 Name: proportion, dtype: float64,
 True     720
 False    213
 Name: count, dtype: int64)

In [71]:
(complete_data.citizenship==complete_data.representing).value_counts(normalize=True), (complete_data.citizenship==complete_data.representing).value_counts(normalize=False)

(True     0.696677
 False    0.303323
 Name: proportion, dtype: float64,
 True     650
 False    283
 Name: count, dtype: int64)

In [97]:
complete_data.groupby('representing')[['citizenship','representing']].